import type { Metadata } from "next";
import { Inter , Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/new/navbar/navbar";
import { Footer } from "@/components/new/footer/footer";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from 'sonner';

const inter = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html className="" lang="en">
      <head>
        <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
      </head>
      <body className={inter.className}>
      <Navbar />
        {children}
        <Toaster position="top-center" richColors />
      </body>
    </html>
    </ClerkProvider>
  );
}
